### ISSUE TITLE
`nu_plugin_net` does not appear to work in `0.74`

### ISSUE THREAD

**Issue by amtoine** [nushell/awesome-nu#14]
i'm having trouble installing `nu_plugin_net` as a plugin :open_mouth: 

> **Note**  
> see https://github.com/fennewald/nu_plugin_net/issues/4 for more information

> **Warning**  
> the protocol used by the plugin appears not to be in `nushell`'s plugin system anymore,
> even the `--encoding (-e)` option does not exist anymore for `register`...

**maybe this plugin should be removed from the list?** :thinking: 

## additional information
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.1                                                           |
| branch             | main                                                             |
| commit_hash        | b004aacd691de4c5c976d430eb3a2387e6aec235                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.1                                                           |
| build_time         | 2023-01-14 10:34:36 +01:00                                       |
| build_rust_channel | release                                                          |
| features           | database, default, trash, which, zip                             |
| installed_plugins  | gstat                                                            |

**Comment by fdncred** [comment]
This is one of the reasons I created https://github.com/fdncred/nu_plugin_pnet. It's identical but updated, although I haven't updated it for 0.74 yet.

**Comment by amtoine** [comment]
oh `pnet` is the evolution of `net` :open_mouth: 

i find the sentence
> Same as above but named pnet as to not conflict with Windows net built-in.

a bit confusing then :confused: 
it made me think it was different than `net` :cry:
